config/routes.rb
Rails.application.routes.draw do
  get 'encodingsv/index'

  get 'encodingsv/new'

  get 'encodingsv/show'

  get 'decodings/index'

  get 'decodings/new'

  post 'decodings/show'
  get 'decodings/show'

  get 'encodings/index'

  get 'encodings/new'

  post 'encodings/show'
  get 'encodings/show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decodings_controller.rb
class DecodingsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
  end

  def new
  end

  def show
    @decoded_message = Caesar.decode(params[:shift], params[:message])
  end

end

app/controllers/encodings_controller.rb
class EncodingsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  # ensures not trying to call things outside of application

  def index

  end

  def new
  end

  def show
    # params = {'message' => 'hello world', 'shift' => "s"}
    @message = Caesar.encode(params[:shift], params[:message])
  end
end

app/controllers/encodingsv_controller.rb
class EncodingsvController < ApplicationController
  def index
  end

  def new
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decodings_helper.rb
module DecodingsHelper
end

app/helpers/encodings_helper.rb
module EncodingsHelper
end

app/helpers/encodingsv_helper.rb
module EncodingsvHelper
end

app/views/decodings/index.html.erb
<h1>Decodings#index</h1>
<p><%= link_to "Decode a Message", decodings_new_path %></p>

app/views/decodings/new.html.erb
<h1>Decode a Message</h1>

<form action="show" method="post" accept-charset="utf-8">
  <label for="shift"> Letter to Offset: </label>
  <input type="text" name="shift" id="shift" >

  <label for="message"> Your Message To Decode: </label>
  <input type="text" name="message" id="message" >

  <input type="submit" value="Decode!">

</form>

app/views/decodings/show.html.erb
<h1>Result</h1>
<p><%= @decoded_message %></p>

app/views/encodings/index.html.erb
<h1>Encodings#index</h1>
<p><%= link_to "Encode a Message", encodings_new_path %></p>

app/views/encodings/new.html.erb
<h1>Encode a Message</h1>

<form action="show" method="post" accept-charset="utf-8">
  <label for="shift"> Letter to Offset: </label>
  <input type="text" name="shift" id="shift" >

  <label for="message"> Your Message: </label>
  <input type="text" name="message" id="message" >

  <input type="submit" value="Encode!">

</form>

app/views/encodings/show.html.erb
<h1>Result</h1>
<p><%= @message %></p>

app/views/encodingsv/index.html.erb
<h1>Encodingsv#index</h1>
<p>Find me in app/views/encodingsv/index.html.erb</p>

app/views/encodingsv/new.html.erb
<h1>Encodingsv#new</h1>
<p>Find me in app/views/encodingsv/new.html.erb</p>

app/views/encodingsv/show.html.erb
<h1>Encodingsv#show</h1>
<p>Find me in app/views/encodingsv/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaesarCipher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>